config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'

  resource :albums

  get 'sound_track_info/index'

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  end
  def index
  end

  def create
    @album = Album.new(filter_params(params))
    @album.save!
    redirect_to @album
  end

  def show
    @album = Album.find(params[:id])
  end

private

  def filter_params params
    params.require(:album).permit(:name, :caption, :laguage, :director, :budget, :write, :country)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sound_track_info_controller.rb
class SoundTrackInfoController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sound_track_info_helper.rb
module SoundTrackInfoHelper
end

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/index.html.haml
.row-fluid
  .span3
    %div SUMANTH
  .span9
    %div HHHH

app/views/albums/new.html.haml
= form_for :album, url: albums_path do |f|
  %fieldset.well
    .field.form-group
      = f.label :name
    .col-sm-10
      = f.text_field :name
    .field.form-group
      = f.label :caption
    .col-sm-10
      = f.text_field :caption
    .field.form-group
      = f.label :year
    .col-sm-10
      = f.text_field :year
    .field.form-group
      = f.label :language
    .col-sm-10
      = f.text_field :language
    .field.form-group
      = f.label :director
    .col-sm-10
      = f.text_field :director
    .field.form-group
      = f.label :budget
    .col-sm-10
      = f.text_field :budget
    .field.form-group
      = f.label :writer
    .col-sm-10
      = f.text_field :write
    .field.form-group
      = f.label :country
    .col-sm-10
      = f.text_field :country
    = f.submit "Save Album"

app/views/layouts/_navigation.html.haml
#top-site-label
  = link_to "ISDB", root_path, :class => 'brand'
  .dropdown
    %ul.dropdown-menu
      %li
        = link_to "About", "#", :class => 'about-page-link'
= text_field_tag 'product_search', '', :class => 'search-query pull-right', :placeholder => 'Search here', data: {provide: 'typeahead', link: "/home/search_products"}
%ul.nav
  %li
    = link_to 'Sign up', "#"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:rel => "icon", :type => "image/x-icon", :href => "/assets/favicon.ico"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "ISDB"
      %meta{:content => content_for?(:description) ? yield(:description) : "ISDB", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
      %script{type: "text/javascript", src: "http://j.maxmind.com/app/geoip.js"}
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
          #element_to_pop_up 
    .container-fluid
      .row-fluid
        .span12
          = yield
    %nav.modal-footer
      isdb. &copy; Copyright 2013.
      / ! end of .container
    / ! end of #main